spring:
  datasource:
    url: jdbc:clickhouse://103.242.3.92:8123/demo?user=admin&password=EW4KNk6lFAHw3YptdvmV&compress=0
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
    hikari:
      maximum-pool-size: 1000       # High pool size for handling many concurrent connections
      minimum-idle: 100             # Keep enough idle connections for instant reuse
      connection-timeout: 30000     # 30 seconds to avoid blocking threads
      validation-timeout: 3000      # 3 seconds to check connection validity
      idle-timeout: 600000         # 10 minutes for idle connections before closing them
      max-lifetime: 1800000        # 30 minutes to avoid stale connections
      leak-detection-threshold: 10000  # 10 seconds to catch connection leaks
      connection-test-query: "SELECT 1"  # Validate connections with a simple query
      pool-name: "HighConcurrencyPool"  # Custom name for the pool
springdoc:
  swagger-ui:
    path: /swagger-ui.html

############################for dehub
debug: true
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.jdbc: DEBUG
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG
    com.clickhouse: DEBUG
